// <auto-generated />
namespace Muli_Pariwar_Lagat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PDF : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PDF));
        
        string IMigrationMetadata.Id
        {
            get { return "201806280905060_PDF"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
